## Sentiment Analysis on Arts, Crafts, and Sewing Reviews

In [1]:
import pandas as pd 
df = pd.read_json("C:\\Users\\123ch\\Dropbox\\PC\\Downloads\\Arts_Crafts_and_Sewing_5.json", lines=True) # Load the dataset
df.sample(10) # Display a sample of 10 rows

,overall,verified,reviewTime,reviewerID,asin,style,reviewerName,reviewText,summary,unixReviewTime,vote,image
59746,3,True,"10 10, 2015",A2R459D1HKKHG7,B000YZAO2K,{'Size:': ' 1 Pack'},Yvonne C.,good design and idea! but quality should be im...,Three Stars,1444435200,NaN,NaN
378830,2,True,"09 20, 2016",A16LRJC28R50FS,B00YU7T7NU,NaN,KATOPIA,I found it to be no different from the regular...,I love Silhouette but not this blade,1474329600,NaN,NaN
487745,5,True,"03 6, 2016",A3G14Y9Q6P3YM7,B014RZ20II,NaN,Dawn,Love that these come in so many sizes for laye...,Five Stars,1457222400,NaN,NaN
196237,5,True,"04 26, 2016",A2RXQST6DMZWMQ,B003L1MJWC,NaN,Amazon Customer,just what I needed,Five Stars,1461628800,NaN,NaN
444715,5,True,"04 30, 2015",A3NX40QFNZ8KTW,B0055DDUI6,NaN,James Ealy,good for wind chimes,Five Stars,1430352000,NaN,NaN
27865,5,True,"02 16, 2014",AQOZZVUJXIKIR,B000KNI1IU,"{'Size:': ' 8 oz', 'Style Name:': ' Airbrush M...",April,"I'm still a bit of a novice with airbrushing, ...",A much better thinner than water or window cle...,1392508800,3,NaN
2463,5,False,"03 19, 2016",AMMU9VZZ9OSII,B00006IFN8,"{'Size:': ' 8""'}",Dude,I haven't gone wrong with Fiskars...ever...\n\...,Cant go wrong with Fiskars,1458345600,NaN,NaN
121570,5,True,"04 26, 2014",A1T5F9JMWQ6H63,B0016825RG,NaN,KT,ALL CLOVER PRODUCTS ARE FANTASTIC!! I've neve...,Clover Pins,1398470400,NaN,NaN
338147,2,True,"02 15, 2018",A25I292E96CYB0,B00KHAX960,"{'Size:': ' 8-Inch', 'Color:': ' Gold'}",Bets&#039;,Disappointed. Much thinner metal and more expe...,"Thin, expensive, broke",1518652800,NaN,NaN
36829,5,True,"10 11, 2013",A3E5V5TSTAY3R9,B000SN7J7Q,{'Color:': ' Nt Silver'},Rather be at the Beach,I love Artistic Wire! This is the highest qua...,Really Good Wire for Jewelry Making,1381449600,2,NaN

## Geting the Bing Liu lexicon

In [2]:
# Importing necessary libraries
from sklearn import preprocessing
import nltk
nltk.download('opinion_lexicon')
from nltk.corpus import opinion_lexicon
from nltk.tokenize import word_tokenize

print('Total number of words in opinion lexicon', len(opinion_lexicon.words()))
print('Examples of positive words in opinion lexicon',
      opinion_lexicon.positive()[:10])
print('Examples of negative words in opinion lexicon',
      opinion_lexicon.negative()[:10])

Total number of words in opinion lexicon 6789
Examples of positive words in opinion lexicon ['a+', 'abound', 'abounds', 'abundance', 'abundant', 'accessable', 'accessible', 'acclaim', 'acclaimed', 'acclamation']
Examples of negative words in opinion lexicon ['2-faced', '2-faces', 'abnormal', 'abolish', 'abominable', 'abominably', 'abominate', 'abomination', 'abort', 'aborted']

[nltk_data] Downloading package opinion_lexicon to
[nltk_data]     C:\Users\123ch\AppData\Roaming\nltk_data...
[nltk_data]   Package opinion_lexicon is already up-to-date!

## Create the “Dictionary"

In [3]:
# Let's create a dictionary which we can use for scoring our review text
nltk.download('punkt')
df.rename(columns={"reviewText": "text"}, inplace=True)
pos_score = 1
neg_score = -1
word_dict = {}
 
# Adding the positive words to the dictionary
for word in opinion_lexicon.positive():
        word_dict[word] = pos_score
      
# Adding the negative words to the dictionary
for word in opinion_lexicon.negative():
        word_dict[word] = neg_score

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\123ch\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

In [4]:
def bing_liu_score(text):
    sentiment_score = 0
    bag_of_words = word_tokenize(text.lower())
    for word in bag_of_words:
        if word in word_dict:
            sentiment_score += word_dict[word]
    return sentiment_score

In [5]:
df['text'].fillna('no review', inplace=True)
df['Bing_Liu_Score'] = df['text'].apply(bing_liu_score)

In [6]:
df[['overall',"text", 'Bing_Liu_Score']].head(10)

   overall                                               text  Bing_Liu_Score
0        4                Contains some interesting stitches.               1
1        5  I'm a fairly experienced knitter of the one-co...              22
2        4  Great book but the index is terrible. Had to w...               0
3        5  I purchased the Kindle edition which is incred...               4
4        5  Very well laid out and very easy to read.\n\nT...               5
5        5  Beginning her career as a freelance knitter, M...              15
6        5  This is a terrific stitch handbook (and I have...               9
7        4  The book needs to be coil bound. The content i...               1
8        5  I really am enjoying this book! I like the siz...              12
9        5  Just received this book and looked over it cov...               6

In [7]:
df.groupby('overall').agg({'Bing_Liu_Score':'mean'})

         Bing_Liu_Score
overall
1             -0.253030
2              0.567350
3              1.157783
4              2.025464
5              2.125895